### ISSUE TITLE
add_pointer method bugged?

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/flist#2]
Dear @jacobwilliams 

I am studying deeply your wonderful list. Inspecting the `add_pointer` method I think I have found a possible bug (indeed, there are quite low possibilities that is really a bug, rather I am misunderstanding your algorithm). Your method firstly removes the pointer with the passed key if already present, see line

https://github.com/jacobwilliams/flist/blob/master/src/linked_list_module.f90#L554

Only after this optional deletion (that could or not happen) you add the new node, but you _always_ increment the number of nodes count, see line

https://github.com/jacobwilliams/flist/blob/master/src/linked_list_module.f90#L566

 This increment happens even when a previous deletion happened. Is this correct? Should the count be incremented **only** if the deletion happened? My first idea was to patch the algorithm as

``` fortran
call me%get_node(key,p)
if (associated(p)) then
  call me%remove_by_pointer(p)
  ! do not increment the nodes count because the removed node will be replaced by the new one
else
  ! nothing to remove, the nodes count must be incremented
  me%count =  me%count + 1
endif
! remove the line 566
```

This was my understanding, but my concern (due to my pain when dealing with pointers) is that I misunderstood your logic. Can you give some feedback?

Cheers.

P.S. are you using this list implementation (or one derived from this) into json-fortran?

**Comment by jacobwilliams** [comment]
No, I think mine is correct because the `remove_by_pointer` routine has

``` fortran
        me%count = me%count - 1
```

So, it gets decremented when removed and then incremented when added back.

**Comment by szaghi** [comment]
@jacobwilliams Yes, I see now the _decrement_ in remove method, sorry!
