### ISSUE TITLE
traverse method, unused variables?

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/flist#3]
Dear @jacobwilliams 

I am sorry to bother you, feel free to :gun: me if I am too much bothering...

Into the method `traverse` (https://github.com/jacobwilliams/flist/blob/master/src/linked_list_module.f90#L191) the local variables `p` and `done` are not used or at least look like to be not used. Can you confirm? Maybe a cut/paste garbage from `traverse_list` method?

This concern of mine is related to my _misunderstanding_ of your iterators logic... but I'll open another issue to ask your help on this :smile:

Cheers.

**Comment by jacobwilliams** [comment]
You're right. Looks like a copy and paste.
